// client/src/components/Header.tsx
import { Link, useLocation } from 'react-router-dom';
import { IoMdArrowRoundBack } from 'react-icons/io';
import Icon from './ui/Icon';

declare const NL_APPVERSION: string;

function Header() {
    const location = useLocation();
    const showArrow = location.pathname !== '/';
    const version = NL_APPVERSION;

    return (
        <header className="flex justify-center gap-0.5 text-3xl font-bold text-cta mt-4 flex-col items-center">
            {showArrow && (
                <Link to="/" className="absolute left-10 top-10">
                    <Icon icon={IoMdArrowRoundBack} />
                </Link>
            )}
            NodewarGG x Ikusa
            <span className="text-xs font-light">
                v {version}
            </span>
        </header>
    );
}

export default Header;

// ui/src/components/header.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import Icon from '../svelte-ui/elements/icon.svelte';
	import IoMdArrowRoundBack from 'svelte-icons/io/IoMdArrowRoundBack.svelte';

	$: show_arrow = $page.route.id !== '/';

	const version = NL_APPVERSION;
</script>

<header class="flex items-center justify-center">
	<div class="flex gap-2 items-end">
		<a class="text-3xl font-bold text-gold mt-8 flex flex-col items-center" href={'/'}>
			{#if show_arrow}
				<div class="absolute left-1/2 -translate-x-16 translate-y-2">
					<Icon icon={IoMdArrowRoundBack} />
				</div>
			{/if}
			Ikusa x NodewarGG
			<span class="text-xs font-light">Logger <span class="text-xs">{version}</span></span>
		</a>
	</div>
</header>
