// ui/src/svelte-ui/elements/button.svelte
<script lang="ts">
	import { Button } from 'flowbite-svelte';
	interface $$Props {
		class?: string;
		id?: string;
		color?: 'primary' | 'secondary';
		disabled?: boolean;
		size?: 'sm' | 'md' | 'lg';
	}
</script>

<Button
	on:click
	disabled={$$props.disabled || false}
	id={$$props.id}
	btnClass="
	{($$props.color === 'primary' || !$$props.color) &&
		`bg-gold-300 focus:ring-gold-400 text-black ${
			$$props.disabled ? '!bg-gray-700 text-gray-400' : 'border-gold'
		}`}
	{$$props.color === 'secondary' &&
		'bg-background focus:ring-gray-400 border border-foreground-secondary'}
	text-center font-medium focus:ring-4 focus:outline-none flex items-center justify-center rounded-lg {$$props.class}
	{($$props.size === 'md' || !$$props.size) && 'h-10 px-5 text-sm'}
	{$$props.size === 'sm' && 'h-8 px-4 text-xs'}
	{$$props.size === 'lg' && 'h-12 px-6 text-lg'}
	"
>
	<slot />
</Button>

// client/src/components/ui/Button.tsx
import { ButtonHTMLAttributes } from 'react';
import classNames from 'classnames';

interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
    color?: 'primary' | 'secondary';
    size?: 'sm' | 'md' | 'lg';
}

function Button({
    children,
    className,
    color = 'primary',
    size = 'md',
    disabled,
    ...props
}: ButtonProps) {
    const buttonClasses = classNames(
        'text-center font-medium focus:ring-4 focus:outline-none flex items-center justify-center rounded-lg',
        {
            'bg-gold-300 focus:ring-gold-400 text-black border-gold': color === 'primary' && !disabled,
            '!bg-gray-700 text-gray-400': color === 'primary' && disabled,
            'bg-background focus:ring-gray-400 border border-foreground-secondary': color === 'secondary',
            'h-8 px-4 text-xs': size === 'sm',
            'h-10 px-5 text-sm': size === 'md',
            'h-12 px-6 text-lg': size === 'lg'
        },
        className
    );

    return (
        <button className={buttonClasses} disabled={disabled} {...props}>
            {children}
        </button>
    );
}

export default Button;
